# Generated by Django 6.0.1 on 2026-03-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='website',
        ),
    ]
